"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import Image from "next/image";
import { Building2, Users, Plug, Settings, FileText, CheckCircle, Loader2, ArrowRight, ArrowLeft, Send } from "lucide-react";

interface ClientInfo { id: string; company_name: string; contact_name: string; email: string; industry: string; website: string; plan_name: string; onboarding_status: string; }
const STEPS = [
  { id: 1, title: "Business Details", description: "Tell us about your business" },
  { id: 2, title: "Your Team", description: "Who will use the automation?" },
  { id: 3, title: "Integrations", description: "Connect your existing tools" },
  { id: 4, title: "Preferences", description: "How should we configure things?" },
  { id: 5, title: "Review & Submit", description: "Confirm your details" },
];
const IC = "w-full px-3 py-2.5 rounded-lg bg-[var(--color-surface)] border border-[var(--color-border)] text-[var(--color-text-primary)] text-sm placeholder:text-[var(--color-text-muted)] focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)]/50 focus:border-[var(--color-accent)] transition-colors";
function F({ l, r, children }: { l: string; r?: boolean; children: React.ReactNode }) { return <div><label className="block text-xs font-medium text-[var(--color-text-secondary)] mb-1.5">{l} {r && <span className="text-[var(--color-error)]">*</span>}</label>{children}</div>; }

export default function OnboardingPage() {
  const params = useParams();
  const cid = params.clientId as string;
  const [cl, setCl] = useState<ClientInfo | null>(null);
  const [ld, setLd] = useState(true);
  const [sub, setSub] = useState(false);
  const [done, setDone] = useState(false);
  const [err, setErr] = useState("");
  const [st, setSt] = useState(1);
  const [f, setF] = useState({
    business_name:"", industry:"", website:"", timezone:"Africa/Lagos",
    primary_contact_name:"", primary_contact_email:"", primary_contact_phone:"", primary_contact_role:"Owner",
    secondary_contact_name:"", secondary_contact_email:"",
    whatsapp_number:"", whatsapp_provider:"", email_smtp:"", calendar_provider:"", calendar_url:"", crm_tool:"",
    working_hours_start:"09:00", working_hours_end:"17:00", working_days:["mon","tue","wed","thu","fri"],
    response_speed:"instant", follow_up_1_hours:4, follow_up_2_hours:24, follow_up_3_hours:72,
    greeting_message:"", team_size:"", current_tools:"", biggest_challenge:"", additional_notes:"",
  });
  useEffect(() => {
    fetch("/api/onboarding/" + cid).then(r => r.json()).then(d => {
      if (d.client) { setCl(d.client); if (d.client.onboarding_status === "completed") setDone(true); }
      else setErr("Client not found.");
    }).catch(() => setErr("Failed to load.")).finally(() => setLd(false));
  }, [cid]);
  const uf = (k: string, v: string | number | string[]) => setF(p => ({...p, [k]: v}));
  const td = (d: string) => setF(p => ({...p, working_days: p.working_days.includes(d) ? p.working_days.filter(x => x !== d) : [...p.working_days, d]}));
  async function submit() {
    setSub(true); setErr("");
    try { const r = await fetch("/api/onboarding/" + cid, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(f) }); const d = await r.json(); if (d.success) setDone(true); else setErr(d.error || "Failed."); }
    catch { setErr("Network error."); }
    finally { setSub(false); }
  }
  if (ld) return <div className="min-h-screen bg-[var(--color-surface)] flex items-center justify-center"><Loader2 className="w-8 h-8 text-[var(--color-accent)] animate-spin" /></div>;
  if (err && !cl) return <div className="min-h-screen bg-[var(--color-surface)] flex items-center justify-center p-4"><div className="max-w-sm text-center"><Image src="/brand/elion-e-icon.svg" alt="ELION" width={48} height={48} className="mx-auto mb-4" /><h1 className="text-lg font-bold text-[var(--color-text-primary)] mb-2">Onboarding</h1><p className="text-sm text-[var(--color-error)]">{err}</p></div></div>;
  if (done) return <div className="min-h-screen bg-[var(--color-surface)] flex items-center justify-center p-4"><div className="max-w-md text-center"><div className="w-16 h-16 rounded-full bg-[var(--color-success)]/10 flex items-center justify-center mx-auto mb-6"><CheckCircle className="w-8 h-8 text-[var(--color-success)]" /></div><h1 className="text-xl font-bold text-[var(--color-text-primary)] mb-3">Onboarding Complete</h1><p className="text-sm text-[var(--color-text-muted)] mb-6">Thank you. We have received your details and will contact you within 24 hours.</p><div className="p-4 rounded-lg bg-[var(--color-surface-raised)] border border-[var(--color-border)] text-left"><p className="text-xs font-semibold text-[var(--color-text-muted)] uppercase tracking-wider mb-2">What happens next</p><ol className="space-y-2 text-sm text-[var(--color-text-secondary)]"><li>1. We review your details</li><li>2. We configure your automations</li><li>3. We set up your dashboard</li><li>4. We send login credentials</li></ol></div></div></div>;
  return (<div className="min-h-screen bg-[var(--color-surface)]">
    <header className="border-b border-[var(--color-border)]"><div className="max-w-2xl mx-auto px-4 py-4 flex items-center justify-between"><div className="flex items-center gap-2"><Image src="/brand/elion-e-icon.svg" alt="ELION" width={24} height={24} /><span className="font-bold text-sm text-[var(--color-text-primary)]" style={{fontFamily:"Space Grotesk,sans-serif"}}>ELION</span></div><span className="text-xs text-[var(--color-text-muted)]">Client Onboarding</span></div></header>
    <div className="max-w-2xl mx-auto px-4 py-8">
      <div className="mb-8"><h1 className="text-xl font-bold text-[var(--color-text-primary)] mb-1">Welcome to ELION</h1><p className="text-sm text-[var(--color-text-muted)]">Hi {cl?.contact_name || "there"}, let us set up your automation. This takes about 5 minutes.</p></div>
      <div className="flex items-center gap-2 mb-8">{STEPS.map((s,i)=>(<div key={s.id} className="flex items-center gap-2 flex-1"><div className={"w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold shrink-0 "+(st>s.id?"bg-[var(--color-success)]/20 text-[var(--color-success)]":st===s.id?"bg-[var(--color-accent)]/20 text-[var(--color-accent)]":"bg-[var(--color-surface-raised)] text-[var(--color-text-muted)]")}>{st>s.id?<CheckCircle className="w-4 h-4"/>:s.id}</div>{i<STEPS.length-1&&<div className={"flex-1 h-0.5 "+(st>s.id?"bg-[var(--color-success)]/30":"bg-[var(--color-border)]")}/>}</div>))}</div>
      <div className="mb-6"><h2 className="text-lg font-semibold text-[var(--color-text-primary)]">{STEPS[st-1].title}</h2><p className="text-xs text-[var(--color-text-muted)] mt-0.5">{STEPS[st-1].description}</p></div>
      {err&&<div className="p-3 rounded-lg bg-[var(--color-error)]/10 border border-[var(--color-error)]/20 mb-6"><p className="text-sm text-[var(--color-error)]">{err}</p></div>}
      {st===1&&<div className="space-y-4"><F l="Business Name" r><input value={f.business_name} onChange={e=>uf("business_name",e.target.value)} className={IC} placeholder="e.g. Premier Realty"/></F><F l="Industry"><select value={f.industry} onChange={e=>uf("industry",e.target.value)} className={IC}><option value="">Select industry</option><option value="real_estate">Real Estate</option><option value="ecommerce">E-commerce</option><option value="professional_services">Professional Services</option><option value="healthcare">Healthcare</option><option value="education">Education</option><option value="hospitality">Hospitality</option><option value="technology">Technology</option><option value="finance">Finance</option><option value="other">Other</option></select></F><F l="Website"><input value={f.website} onChange={e=>uf("website",e.target.value)} className={IC} placeholder="https://yourbusiness.com"/></F><F l="Timezone"><select value={f.timezone} onChange={e=>uf("timezone",e.target.value)} className={IC}><option value="Africa/Lagos">WAT</option><option value="Europe/London">GMT</option><option value="America/New_York">ET</option></select></F></div>}
      {st===2&&<div className="space-y-4"><F l="Full Name" r><input value={f.primary_contact_name} onChange={e=>uf("primary_contact_name",e.target.value)} className={IC} placeholder="Your full name"/></F><F l="Email" r><input value={f.primary_contact_email} onChange={e=>uf("primary_contact_email",e.target.value)} className={IC} placeholder="you@company.com" type="email"/></F><F l="Phone"><input value={f.primary_contact_phone} onChange={e=>uf("primary_contact_phone",e.target.value)} className={IC} placeholder="+234 800 000 0000"/></F><F l="Role"><select value={f.primary_contact_role} onChange={e=>uf("primary_contact_role",e.target.value)} className={IC}><option value="Owner">Owner</option><option value="Manager">Manager</option><option value="Director">Director</option></select></F></div>}
      {st===3&&<div className="space-y-4"><F l="WhatsApp"><input value={f.whatsapp_number} onChange={e=>uf("whatsapp_number",e.target.value)} className={IC} placeholder="+234 800 000 0000"/></F><F l="Email"><select value={f.email_smtp} onChange={e=>uf("email_smtp",e.target.value)} className={IC}><option value="">Not configured</option><option value="gmail">Gmail</option><option value="outlook">Outlook</option><option value="zoho">Zoho</option><option value="other">Other</option></select></F><F l="Calendar"><select value={f.calendar_provider} onChange={e=>uf("calendar_provider",e.target.value)} className={IC}><option value="">Not configured</option><option value="google_calendar">Google Calendar</option><option value="calendly">Calendly</option><option value="other">Other</option></select></F><F l="CRM"><select value={f.crm_tool} onChange={e=>uf("crm_tool",e.target.value)} className={IC}><option value="">No CRM</option><option value="hubspot">HubSpot</option><option value="google_sheets">Google Sheets</option><option value="other">Other</option></select></F></div>}
      {st===4&&<div className="space-y-4"><F l="Hours"><div className="flex items-center gap-2"><input type="time" value={f.working_hours_start} onChange={e=>uf("working_hours_start",e.target.value)} className={IC+" flex-1"}/><span className="text-xs text-[var(--color-text-muted)]">to</span><input type="time" value={f.working_hours_end} onChange={e=>uf("working_hours_end",e.target.value)} className={IC+" flex-1"}/></div></F><F l="Days"><div className="flex flex-wrap gap-2">{["mon","tue","wed","thu","fri","sat","sun"].map(d=>(<button key={d} type="button" onClick={()=>td(d)} className={"px-3 py-1.5 rounded text-xs font-medium transition-colors cursor-pointer "+(f.working_days.includes(d)?"bg-[var(--color-accent)]/20 text-[var(--color-accent)] border border-[var(--color-accent)]/30":"bg-[var(--color-surface-raised)] text-[var(--color-text-muted)] border border-[var(--color-border)]")}>{d.slice(0,3)}</button>))}</div></F><F l="Response"><select value={f.response_speed} onChange={e=>uf("response_speed",e.target.value)} className={IC}><option value="instant">Instant</option><option value="fast">Fast</option><option value="business_hours">Business hours</option></select></F><F l="Follow-ups"><div className="space-y-2"><div className="flex items-center gap-2"><span className="text-xs text-[var(--color-text-muted)] w-16">1st</span><select value={f.follow_up_1_hours} onChange={e=>uf("follow_up_1_hours",Number(e.target.value))} className={IC+" flex-1"}><option value={1}>1h</option><option value={4}>4h</option><option value={8}>8h</option><option value={24}>24h</option></select></div><div className="flex items-center gap-2"><span className="text-xs text-[var(--color-text-muted)] w-16">2nd</span><select value={f.follow_up_2_hours} onChange={e=>uf("follow_up_2_hours",Number(e.target.value))} className={IC+" flex-1"}><option value={24}>24h</option><option value={48}>48h</option><option value={72}>72h</option></select></div><div className="flex items-center gap-2"><span className="text-xs text-[var(--color-text-muted)] w-16">3rd</span><select value={f.follow_up_3_hours} onChange={e=>uf("follow_up_3_hours",Number(e.target.value))} className={IC+" flex-1"}><option value={72}>72h</option><option value={168}>7 days</option></select></div></div></F><F l="Greeting"><textarea value={f.greeting_message} onChange={e=>uf("greeting_message",e.target.value)} className={IC} rows={2} placeholder="e.g. Thank you for contacting us!"/></F></div>}
      {st===5&&<div className="space-y-4"><div className="p-4 rounded-lg bg-[var(--color-surface-raised)] border border-[var(--color-border)]"><h3 className="text-sm font-semibold text-[var(--color-text-primary)] mb-3">Summary</h3><div className="grid grid-cols-2 gap-3 text-xs"><div><span className="text-[var(--color-text-muted)]">Name:</span> <span className="text-[var(--color-text-secondary)]">{f.business_name||"-"}</span></div><div><span className="text-[var(--color-text-muted)]">Industry:</span> <span className="text-[var(--color-text-secondary)]">{f.industry||"-"}</span></div><div><span className="text-[var(--color-text-muted)]">Contact:</span> <span className="text-[var(--color-text-secondary)]">{f.primary_contact_name||"-"}</span></div><div><span className="text-[var(--color-text-muted)]">Email:</span> <span className="text-[var(--color-text-secondary)]">{f.primary_contact_email||"-"}</span></div></div></div><F l="Notes"><textarea value={f.additional_notes} onChange={e=>uf("additional_notes",e.target.value)} className={IC} rows={2} placeholder="Anything else..."/></F></div>}
      <div className="flex items-center justify-between mt-8 pt-6 border-t border-[var(--color-border)]">{st>1?<button onClick={()=>setSt(st-1)} className="flex items-center gap-1.5 px-4 py-2 text-sm text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] transition-colors cursor-pointer"><ArrowLeft className="w-4 h-4"/> Back</button>:<div/>}{st<STEPS.length?<button onClick={()=>setSt(st+1)} disabled={st===1&&!f.business_name} className="flex items-center gap-1.5 px-5 py-2.5 rounded-lg bg-[var(--color-accent)] text-white text-sm font-semibold hover:bg-[var(--color-accent-hover)] disabled:opacity-50 disabled:cursor-not-allowed transition-colors cursor-pointer">Continue <ArrowRight className="w-4 h-4"/></button>:<button onClick={submit} disabled={sub} className="flex items-center gap-1.5 px-5 py-2.5 rounded-lg bg-[var(--color-accent)] text-white text-sm font-semibold hover:bg-[var(--color-accent-hover)] disabled:opacity-50 disabled:cursor-not-allowed transition-colors cursor-pointer">{sub?<Loader2 className="w-4 h-4 animate-spin"/>:<Send className="w-4 h-4"/>}{sub?"Submitting...":"Submit"}</button>}</div>
    </div>
  </div>);
}