"use client";

import { Search, Zap, Mail, RotateCcw, Calendar, Settings, ArrowRight, TrendingUp, Users, Activity, DollarSign, Globe, FileText } from "lucide-react";
import Link from "next/link";
import { StatCard, Card, Badge, StatusDot } from "@/components/ui";
import { useState } from "react";

const offers = [
  { id: "audit", title: "Automation Leak Audit", description: "Examine customer journey and operations to identify where leads are lost and repetitive tasks waste resources.", icon: Search, href: "/audit", landing: "/landing/audit", color: "text-blue-400", bgColor: "bg-blue-400/10", metrics: { scanned: 47, leaks: 12, saved: "NGN 2.4M" } },
  { id: "leads", title: "Lead Response System", description: "Instant lead intake from any channel. Auto-qualify, score, assign, and follow up within seconds.", icon: Zap, href: "/leads", landing: "/landing/leads", color: "text-amber-400", bgColor: "bg-amber-400/10", metrics: { leads: 1284, responseTime: "3s", conversion: "34%" } },
  { id: "followup", title: "Follow-Up Engine", description: "Multi-step follow-up sequences across email, WhatsApp, and SMS automatically.", icon: Mail, href: "/followup", landing: "/landing/followup", color: "text-emerald-400", bgColor: "bg-emerald-400/10", metrics: { sequences: 23, sent: 4821, replies: 892 } },
  { id: "recovery", title: "Revenue Recovery System", description: "Reactivate dormant leads and old customers with personalized reactivation campaigns.", icon: RotateCcw, href: "/recovery", landing: "/landing/recovery", color: "text-violet-400", bgColor: "bg-violet-400/10", metrics: { dormant: 3420, reactivated: 487, revenue: "NGN 8.2M" } },
  { id: "booking", title: "Booking Engine", description: "Turn enquiries into booked appointments without the back-and-forth.", icon: Calendar, href: "/booking", landing: "/landing/booking", color: "text-rose-400", bgColor: "bg-rose-400/10", metrics: { bookings: 312, noShows: "8%", satisfaction: "96%" } },
  { id: "operations", title: "Operations Automation", description: "Remove repetitive work from your team's day. Data entry, reports, notifications, and more.", icon: Settings, href: "/operations", landing: "/landing/operations", color: "text-cyan-400", bgColor: "bg-cyan-400/10", metrics: { workflows: 18, tasksSaved: 1240, hoursWeekly: 32 } },
];

// Quick report generator
function generateQuickReport() {
  const now = new Date();
  const report = `
    <html><head><title>Elion Weekly Report - ${now.toLocaleDateString()}</title>
    <style>body{font-family:Inter,system-ui,sans-serif;padding:40px;color:#1a1a2e}h1{color:#6366f1}h2{color:#374151;border-bottom:2px solid #e5e7eb;padding-bottom:8px}table{width:100%;border-collapse:collapse;margin:16px 0}th,td{padding:12px;text-align:left;border-bottom:1px solid #e5e7eb}th{background:#f3f4f6;font-weight:600}.metric{background:#f3f4f6;padding:16px;border-radius:8px;text-align:center;margin:8px}.metric h3{font-size:24px;color:#6366f1;margin:0}.metric p{font-size:12px;color:#6b7280;margin:4px 0 0}</style></head><body>
    <h1>Elion AI Agency - Weekly Operations Report</h1>
    <p style="color:#6b7280">Generated: ${now.toLocaleString()}</p>
    <h2>System Overview</h2>
    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px">
      <div class="metric"><h3>1,284</h3><p>Total Leads Processed</p></div>
      <div class="metric"><h3>34.2%</h3><p>Conversion Rate</p></div>
      <div class="metric"><h3>4,821</h3><p>Messages Sent</p></div>
      <div class="metric"><h3>NGN 8.2M</h3><p>Revenue Recovered</p></div>
    </div>
    <h2>Lead Pipeline</h2>
    <table><tr><th>Status</th><th>Count</th><th>Conversion</th></tr>
    <tr><td>New</td><td>127</td><td>-</td></tr>
    <tr><td>Qualified</td><td>89</td><td>70%</td></tr>
    <tr><td>Contacted</td><td>234</td><td>56%</td></tr>
    <tr><td>Meeting</td><td>56</td><td>24%</td></tr>
    <tr><td>Won</td><td>42</td><td>75%</td></tr></table>
    <h2>Active Automations</h2>
    <table><tr><th>System</th><th>Status</th><th>Monthly Savings</th></tr>
    <tr><td>Lead Response</td><td>Active</td><td>NGN 1.2M</td></tr>
    <tr><td>Follow-Up Engine</td><td>Active</td><td>NGN 850K</td></tr>
    <tr><td>Revenue Recovery</td><td>Active</td><td>NGN 6.9M</td></tr>
    <tr><td>Booking Engine</td><td>Active</td><td>NGN 320K</td></tr>
    <tr><td>Operations</td><td>Active</td><td>NGN 390K</td></tr></table>
    <h2>Key Metrics</h2>
    <ul><li>Average Response Time: 2.8s (Target: &lt;3s)</li>
    <li>Email Open Rate: 67.3%</li>
    <li>WhatsApp Reply Rate: 42.1%</li>
    <li>No-Show Rate: 8% (Down from 18%)</li>
    <li>Client Satisfaction: 96%</li></ul>
    <p style="color:#6b7280;margin-top:40px;border-top:1px solid #e5e7eb;padding-top:16px">Generated by Elion AI Agency | elion.ng</p>
    </body></html>
  `;
  const blob = new Blob([report], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `elion-report-${now.toISOString().split("T")[0]}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function DashboardPage() {
  const [notif, setNotif] = useState("");
  const showNotif = (msg: string) => { setNotif(msg); setTimeout(() => setNotif(""), 3000); };

  return (
    <div className="animate-fade-in">
      {notif && <div className="fixed top-4 right-4 z-[100] px-4 py-3 rounded-lg bg-success/10 border border-success/20 text-success text-sm font-medium animate-fade-in shadow-lg">{notif}</div>}
      <div className="mb-8">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-3xl font-bold text-foreground tracking-tight">Dashboard</h1>
            <p className="text-muted-foreground mt-1">Your automation command center. Six systems, one platform.</p>
          </div>
          <div className="flex gap-3">
            <button onClick={() => { generateQuickReport(); showNotif("Report downloaded!"); }} className="inline-flex items-center gap-2 px-4 py-2 bg-secondary text-secondary-foreground text-sm font-medium rounded-lg hover:bg-secondary/80 transition-colors cursor-pointer">
              <FileText className="w-4 h-4" />Generate Report
            </button>
            <Link href="/landing" className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 text-primary text-sm font-medium rounded-lg hover:bg-primary/20 transition-colors">
              <Globe className="w-4 h-4" />View Landing Pages
            </Link>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8 stagger-children">
        <Link href="/leads"><StatCard label="Total Leads Processed" value="1,284" change={23} changeLabel="vs last month" icon={<Users className="w-5 h-5" />} gradient="primary" /></Link>
        <Link href="/followup"><StatCard label="Active Sequences" value="23" change={8} changeLabel="new this week" icon={<Activity className="w-5 h-5" />} gradient="success" /></Link>
        <Link href="/recovery"><StatCard label="Revenue Recovered" value="NGN 8.2M" change={42} changeLabel="vs last quarter" icon={<DollarSign className="w-5 h-5" />} gradient="warning" /></Link>
        <Link href="/operations"><StatCard label="Hours Saved Weekly" value="32" change={12} changeLabel="vs last month" icon={<TrendingUp className="w-5 h-5" />} gradient="primary" /></Link>
      </div>

      <div className="mb-6">
        <h2 className="text-lg font-semibold text-foreground mb-1">Automation Systems</h2>
        <p className="text-sm text-muted-foreground">Each system solves a specific business problem. Click to explore.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 stagger-children">
        {offers.map((offer) => (
          <Link key={offer.id} href={offer.href}>
            <Card hover className="h-full cursor-pointer">
              <div className="flex items-start justify-between mb-4">
                <div className={`w-10 h-10 rounded-lg ${offer.bgColor} flex items-center justify-center`}>
                  <offer.icon className={`w-5 h-5 ${offer.color}`} />
                </div>
                <Badge variant="success"><StatusDot status="active" /> Active</Badge>
              </div>
              <h3 className="text-base font-semibold text-foreground mb-2">{offer.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed mb-4">{offer.description}</p>
              <div className="flex items-center justify-between pt-3 border-t border-border/50">
                <div className="flex gap-4">
                  {Object.entries(offer.metrics).map(([key, val]) => (
                    <div key={key}>
                      <p className="text-xs text-muted-foreground capitalize">{key.replace(/([A-Z])/g, " $1").trim()}</p>
                      <p className="text-sm font-semibold text-foreground">{String(val)}</p>
                    </div>
                  ))}
                </div>
                <div className="flex items-center gap-2">
                  <Link href={offer.landing} onClick={(e) => e.stopPropagation()} className="text-xs text-primary hover:text-primary/80 transition-colors">Landing Page</Link>
                  <ArrowRight className="w-4 h-4 text-muted-foreground" />
                </div>
              </div>
            </Card>
          </Link>
        ))}
      </div>

      <div className="mt-8">
        <Card>
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-base font-semibold text-foreground">Ready to deploy?</h3>
              <p className="text-sm text-muted-foreground mt-1">Connect your WhatsApp Business API, CRM, and email provider to go live.</p>
            </div>
            <Link href="/audit">
              <Badge variant="info" className="cursor-pointer hover:bg-info/20 transition-colors px-4 py-2">Start with Leak Audit</Badge>
            </Link>
          </div>
        </Card>
      </div>
    </div>
  );
}
