"use client";

import { Search, Zap, Mail, RotateCcw, Calendar, Settings, ArrowRight, Globe, FileText } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

const systems = [
  {
    id: "audit",
    title: "Leak Audit",
    description: "Analyse your business and identify where you are losing leads, time, and revenue.",
    icon: Search,
    href: "/audit",
    color: "text-blue-600",
    bgColor: "bg-blue-50",
  },
  {
    id: "leads",
    title: "Lead Response",
    description: "Capture, qualify, and respond to every lead within seconds across all channels.",
    icon: Zap,
    href: "/leads",
    color: "text-amber-600",
    bgColor: "bg-amber-50",
  },
  {
    id: "followup",
    title: "Follow-Up Engine",
    description: "Automated multi-channel follow-up sequences that convert enquiries into customers.",
    icon: Mail,
    href: "/followup",
    color: "text-emerald-600",
    bgColor: "bg-emerald-50",
  },
  {
    id: "recovery",
    title: "Revenue Recovery",
    description: "Reactivate dormant leads and old customers sitting in your database.",
    icon: RotateCcw,
    href: "/recovery",
    color: "text-violet-600",
    bgColor: "bg-violet-50",
  },
  {
    id: "booking",
    title: "Booking Engine",
    description: "Turn enquiries into booked appointments without the back-and-forth.",
    icon: Calendar,
    href: "/booking",
    color: "text-rose-600",
    bgColor: "bg-rose-50",
  },
  {
    id: "operations",
    title: "Operations Automation",
    description: "Remove repetitive work from your team's day. Data entry, reports, and more.",
    icon: Settings,
    href: "/operations",
    color: "text-cyan-600",
    bgColor: "bg-cyan-50",
  },
];

function generateQuickReport() {
  const now = new Date();
  const report = `<!DOCTYPE html><html><head><title>ELIAN Report - ${now.toLocaleDateString()}</title>
<style>body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;padding:40px;max-width:800px;margin:0 auto;color:#18181b}
h1{font-size:20px;margin-bottom:4px}h2{font-size:14px;text-transform:uppercase;letter-spacing:0.05em;color:#71717a;margin-top:32px;border-bottom:1px solid #e4e4e7;padding-bottom:8px}
table{width:100%;border-collapse:collapse;margin:12px 0}th,td{padding:8px 12px;text-align:left;border-bottom:1px solid #f4f4f5;font-size:13px}
th{background:#f4f4f5;font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:0.05em;color:#71717a}
.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e4e4e7;font-size:11px;color:#a1a1aa}
@media print{body{padding:20px}}</style></head><body>
<h1>ELIAN</h1><p style="color:#71717a;font-size:13px">Business Automation Report &bull; ${now.toLocaleDateString()}</p>
<h2>Automation Systems</h2>
<table><tr><th>System</th><th>Status</th><th>Description</th></tr>
<tr><td>Leak Audit</td><td>Available</td><td>Identify business automation opportunities</td></tr>
<tr><td>Lead Response</td><td>Available</td><td>Instant lead capture and response</td></tr>
<tr><td>Follow-Up Engine</td><td>Available</td><td>Automated multi-channel follow-up</td></tr>
<tr><td>Revenue Recovery</td><td>Available</td><td>Reactivate dormant contacts</td></tr>
<tr><td>Booking Engine</td><td>Available</td><td>Automated appointment scheduling</td></tr>
<tr><td>Operations</td><td>Available</td><td>Internal workflow automation</td></tr></table>
<p style="color:#71717a;font-size:12px;margin-top:24px">Connect your systems to see live data. Run a free Leak Audit to get started.</p>
<div class="footer">Generated by ELIAN &bull; elian.ng &bull; ${now.toLocaleString()}</div>
</body></html>`;
  const blob = new Blob([report], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `elian-report-${now.toISOString().split("T")[0]}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function DashboardPage() {
  const [notif, setNotif] = useState("");
  const showNotif = (msg: string) => {
    setNotif(msg);
    setTimeout(() => setNotif(""), 3000);
  };

  return (
    <div className="max-w-6xl mx-auto">
      {notif && (
        <div className="fixed top-4 right-4 z-[100] px-4 py-2.5 bg-emerald-50 border border-emerald-200 text-emerald-700 text-sm font-medium rounded-lg animate-fade-in">
          {notif}
        </div>
      )}

      {/* Header */}
      <div className="flex items-start justify-between mb-8">
        <div>
          <div className="flex items-center gap-2.5 mb-1">
            <div className="w-8 h-8 rounded bg-zinc-900 flex items-center justify-center">
              <span className="text-white text-xs font-bold">E</span>
            </div>
            <h1 className="text-xl font-bold text-zinc-900 tracking-tight">ELIAN</h1>
          </div>
          <p className="text-sm text-zinc-500">Automation command centre</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => {
              generateQuickReport();
              showNotif("Report downloaded");
            }}
            className="inline-flex items-center gap-1.5 px-3 py-2 bg-white border border-zinc-200 text-zinc-600 text-sm font-medium rounded hover:bg-zinc-50 transition-colors cursor-pointer"
          >
            <FileText className="w-4 h-4" />Export
          </button>
          <Link
            href="/landing"
            className="inline-flex items-center gap-1.5 px-3 py-2 bg-white border border-zinc-200 text-zinc-600 text-sm font-medium rounded hover:bg-zinc-50 transition-colors"
          >
            <Globe className="w-4 h-4" />Website
          </Link>
        </div>
      </div>

      {/* Primary CTA */}
      <div className="bg-zinc-900 rounded-lg p-6 mb-8">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-base font-semibold text-white mb-1">Run a Free Leak Audit</h2>
            <p className="text-sm text-zinc-400">Find out where your business is losing leads, time, and money.</p>
          </div>
          <Link
            href="/audit"
            className="inline-flex items-center gap-2 px-5 py-2.5 bg-white text-zinc-900 text-sm font-semibold rounded hover:bg-zinc-100 transition-colors shrink-0"
          >
            <Search className="w-4 h-4" />Start Audit
          </Link>
        </div>
      </div>

      {/* What ELIAN Does */}
      <div className="mb-6">
        <h2 className="text-base font-semibold text-zinc-900">What ELIAN does</h2>
        <p className="text-sm text-zinc-500 mt-0.5">
          ELIAN builds business automations. Businesses lose money through slow follow-up, missed leads,
          inefficient operations, and dormant customers. ELIAN identifies the leak and builds the automation.
        </p>
      </div>

      {/* Automation Systems */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-8 stagger-children">
        {systems.map((sys) => (
          <Link key={sys.id} href={sys.href}>
            <div className="bg-white border border-zinc-200 rounded-lg p-5 hover:border-zinc-300 transition-colors cursor-pointer h-full">
              <div className="flex items-start gap-3 mb-3">
                <div className={`w-9 h-9 rounded-lg ${sys.bgColor} flex items-center justify-center shrink-0`}>
                  <sys.icon className={`w-4 h-4 ${sys.color}`} />
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-zinc-900">{sys.title}</h3>
                  <p className="text-xs text-zinc-500 leading-relaxed mt-0.5">{sys.description}</p>
                </div>
              </div>
              <div className="flex items-center justify-between pt-3 border-t border-zinc-100">
                <span className="text-[10px] font-semibold text-zinc-400 uppercase tracking-wider">No data yet</span>
                <ArrowRight className="w-4 h-4 text-zinc-300" />
              </div>
            </div>
          </Link>
        ))}
      </div>

      {/* Connect Systems */}
      <div className="bg-white border border-zinc-200 rounded-lg p-5">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-sm font-semibold text-zinc-900">Connect your systems</h3>
            <p className="text-xs text-zinc-500 mt-0.5">
              Connect WhatsApp Business API, CRM, and email provider to see live data in your dashboard.
            </p>
          </div>
          <Link
            href="/audit"
            className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-zinc-50 text-zinc-700 text-sm font-medium rounded border border-zinc-200 hover:bg-zinc-100 transition-colors"
          >
            Start with Audit
          </Link>
        </div>
      </div>
    </div>
  );
}
